'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { jsPDF } from 'jspdf';
import { PLATFORMS, calculateProfit } from '@/lib/calculator-engine';
import Features from '@/components/Features';
import FAQ from '@/components/FAQ';

export default function Home() {
  const [platform, setPlatform] = useState('shopify');
  const [inputs, setInputs] = useState<Record<string, number>>({});

    const [blogPosts, setBlogPosts] = useState<any[]>([]);

  useEffect(() => {
    // This reads the posts you published in the Admin Panel
    const allPosts = JSON.parse(localStorage.getItem('blogPosts') || '[]');
    const published = allPosts.filter((p: any) => p.published).reverse();
    setBlogPosts(published);
  }, []);

  const config = PLATFORMS.find(p => p.id === platform)!;
  const result = calculateProfit(platform, inputs);

  const handleChange = (id: string, val: string) => {
    setInputs(prev => ({ ...prev, [id]: parseFloat(val) || 0 }));
  };

  const handleExportCSV = (platformId: string, platformName: string, res: any) => {
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "E-commerce Calculator Report\n";
    csvContent += `Platform,${platformName}\n`;
    csvContent += `Date,${new Date().toLocaleDateString()}\n\n`;
    csvContent += "Metric,Value (Rs.)\n";
    csvContent += `Total Revenue,${res.revenue}\n`;
    csvContent += `Total Expenses,${res.totalExpenses}\n`;
    csvContent += `Net Profit,${res.netProfit}\n`;
    csvContent += `Profit Margin,${res.profitMargin}%\n`;
    csvContent += `ROI,${res.roi}%\n`;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `profit_report_${platformId}_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = (platformId: string, platformName: string, res: any) => {
    const doc = new jsPDF();
    doc.setFontSize(20); doc.setTextColor(99, 102, 241); doc.text("E-commerce Calculator", 20, 20);
    doc.setFontSize(12); doc.setTextColor(100, 100, 100); doc.text(`Platform: ${platformName}`, 20, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 36);
    doc.setDrawColor(200, 200, 200); doc.line(20, 42, 190, 42);
    doc.setFontSize(14); doc.setTextColor(0, 0, 0); doc.text("Financial Summary", 20, 55);
    doc.setFontSize(12); let yPos = 65;
    const addRow = (label: string, value: string, isBold = false) => {
      if (isBold) doc.setFont("helvetica", "bold"); else doc.setFont("helvetica", "normal");
      doc.text(`${label}:`, 20, yPos); doc.text(value, 120, yPos); yPos += 10;
    };
    addRow("Total Revenue", `Rs. ${res.revenue.toLocaleString()}`);
    addRow("Total Expenses", `Rs. ${res.totalExpenses.toLocaleString()}`);
    yPos += 5; addRow("NET PROFIT", `Rs. ${res.netProfit.toLocaleString()}`, true); yPos += 5;
    addRow("Profit Margin", `${res.profitMargin.toFixed(1)}%`);
    addRow("ROI", `${res.roi.toFixed(1)}%`);
    doc.setFontSize(10); doc.setTextColor(150, 150, 150); doc.text("Generated by E-commerce Calculator (100% Free)", 20, 280);
    doc.save(`profit_report_${platformId}_${Date.now()}.pdf`);
  };

  const calculatorsList = [
    { name: 'Profit Calculator', slug: 'profit', icon: '💰' }, { name: 'Margin Calculator', slug: 'margin', icon: '📊' },
    { name: 'ROI Calculator', slug: 'roi', icon: '📈' }, { name: 'ROAS Calculator', slug: 'roas', icon: '🎯' },
    { name: 'Break Even', slug: 'break-even', icon: '⚖️' }, { name: 'Discount Calc', slug: 'discount', icon: '💸' },
    { name: 'Shipping Calc', slug: 'shipping', icon: '' }, { name: 'COD Calculator', slug: 'cod', icon: '💳' },
    { name: 'Tax Calculator', slug: 'tax', icon: '💵' }, { name: 'CPC Calculator', slug: 'cpc', icon: '📉' },
    { name: 'CPA Calculator', slug: 'cpa', icon: '👥' }, { name: 'CPM Calculator', slug: 'cpm', icon: '' },
    { name: 'Revenue Calc', slug: 'revenue', icon: '💰' }, { name: 'Monthly Profit', slug: 'monthly-profit', icon: '📅' },
    { name: 'Yearly Profit', slug: 'yearly-profit', icon: '📆' }, { name: 'Currency Conv', slug: 'currency', icon: '💱' },
    { name: 'Commission', slug: 'commission', icon: '' }, { name: 'Bundle Pricing', slug: 'bundle', icon: '🎁' },
    { name: 'Markup Calculator', slug: 'markup', icon: '🏷️' }, { name: 'Returns Calc', slug: 'returns', icon: '🔄' },
    { name: 'Percentage Calc', slug: 'percentage', icon: '📊' }
  ];

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30">
      <nav className="glass sticky top-0 z-50 border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white font-bold text-sm">EC</div>
            <span className="font-bold text-lg">E-commerce Calculator</span>
          </Link>
          <div className="hidden md:flex gap-6 text-sm text-slate-600">
            <a href="#calc" className="hover:text-indigo-600 transition">Calculators</a>
            <Link href="/blog" className="hover:text-indigo-600 transition">Blog</Link>
            <a href="#about" className="hover:text-indigo-600 transition">About</a>
          </div>
        </div>
      </nav>

      <section className="max-w-4xl mx-auto px-6 pt-20 pb-8 text-center">
        <div className="inline-flex items-center gap-2 bg-green-50 border border-green-200 rounded-full px-4 py-1.5 text-xs font-medium text-green-700 mb-6">
          ✓ 100% FREE • No Signup • No Limits
        </div>
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-4">
          The Ultimate <span className="gradient-text">FREE Seller Toolkit</span>
        </h1>
        <p className="text-lg text-slate-600">Calculate your REAL profit after every expense. 50+ free calculators.</p>
      </section>

      <section id="calc" className="max-w-5xl mx-auto px-6 py-12">
        <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 overflow-hidden glow">
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-8 py-6 text-white">
            <h2 className="text-2xl font-bold">Smart Profit Calculator</h2>
            <p className="text-indigo-100 text-sm mt-1">Select platform & enter your numbers</p>
          </div>
          <div className="px-8 py-4 border-b bg-slate-50 flex gap-2 overflow-x-auto">
            {PLATFORMS.map(p => (
              <button key={p.id} onClick={() => setPlatform(p.id)} className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition ${platform === p.id ? 'bg-slate-900 text-white' : 'bg-white border border-slate-200 hover:border-indigo-400'}`}>
                {p.icon} {p.name}
              </button>
            ))}
          </div>
          <div className="p-8 grid lg:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Your Numbers</h3>
              {config.fields.map(f => (
                <div key={f.id}>
                  <label className="text-sm font-medium text-slate-700 mb-1 block">{f.label}</label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm">Rs</span>
                    <input type="number" value={inputs[f.id] || ''} onChange={e => handleChange(f.id, e.target.value)} placeholder={f.placeholder} className="w-full pl-10 pr-4 py-2.5 border border-slate-200 rounded-lg text-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 outline-none" />
                  </div>
                </div>
              ))}
            </div>
            <div className="bg-gradient-to-br from-slate-900 to-indigo-950 rounded-2xl p-6 text-white">
              <h3 className="text-sm font-medium text-slate-400 mb-4 uppercase tracking-wider">Results</h3>
              <div className="flex justify-between items-end pb-4 border-b border-white/10">
                <span className="text-slate-400">Net Profit</span>
                <span className={`text-4xl font-bold ${result.netProfit >= 0 ? 'text-green-400' : 'text-red-400'}`}>Rs. {result.netProfit.toLocaleString()}</span>
              </div>
              <div className="grid grid-cols-2 gap-4 mt-4 text-sm">
                <div><span className="text-slate-400">Revenue:</span> <span className="font-semibold">Rs. {result.revenue.toLocaleString()}</span></div>
                <div><span className="text-slate-400">Expenses:</span> <span className="font-semibold text-red-400">Rs. {result.totalExpenses.toLocaleString()}</span></div>
                <div><span className="text-slate-400">Margin:</span> <span className="font-semibold">{result.profitMargin.toFixed(1)}%</span></div>
                <div><span className="text-slate-400">ROI:</span> <span className="font-semibold">{result.roi.toFixed(1)}%</span></div>
              </div>
              <div className="flex gap-3 mt-6 pt-4 border-t border-white/10">
                <button onClick={() => handleExportPDF(platform, config.name, result)} className="flex-1 bg-white/10 hover:bg-white/20 py-2 rounded-lg text-sm font-medium transition flex items-center justify-center gap-2"> Download PDF</button>
                <button onClick={() => handleExportCSV(platform, config.name, result)} className="flex-1 bg-white/10 hover:bg-white/20 py-2 rounded-lg text-sm font-medium transition flex items-center justify-center gap-2"> Download CSV</button>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="max-w-6xl mx-auto px-6 py-16">
        <h2 className="text-3xl font-bold text-center mb-2">Popular Calculators</h2>
        <p className="text-slate-600 text-center mb-10">All 100% free. No registration required.</p>
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4 mb-8">
          {calculatorsList.map((c) => (
            <Link key={c.slug} href={`/calculators/${c.slug}`} className="bg-white border border-slate-200 rounded-xl p-4 hover:shadow-lg hover:border-indigo-400 transition hover:-translate-y-1 block">
              <div className="text-xl mb-1">{c.icon}</div>
              <div className="font-semibold text-sm">{c.name}</div>
            </Link>
          ))}
        </div>
        <div className="text-center">
          <button className="border-2 border-slate-200 px-8 py-3 rounded-xl font-semibold hover:border-indigo-500 hover:text-indigo-600 transition bg-white">View All 50+ Calculators →</button>
        </div>
      </section>

            {/* BLOG SECTION - NOW CONNECTED TO ADMIN PANEL */}
      <section id="blog" className="bg-white py-16 border-t border-slate-200">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-10">From the Blog</h2>
          
          {blogPosts.length === 0 ? (
            <div className="text-center py-12 bg-slate-50 rounded-2xl border border-dashed border-slate-300">
              <p className="text-slate-500 mb-4">No published posts yet.</p>
              <Link href="/admin" className="text-indigo-600 font-medium hover:underline">Go to Admin Panel to publish your first article →</Link>
            </div>
          ) : (
            <div className="grid md:grid-cols-3 gap-6">
              {blogPosts.slice(0, 3).map((post) => (
                <div key={post.id} className="border border-slate-200 rounded-xl overflow-hidden hover:shadow-lg transition bg-white flex flex-col">
                  <div className="h-36 bg-gradient-to-br from-indigo-100 to-purple-100 flex items-center justify-center text-4xl">📰</div>
                  <div className="p-5 flex-1 flex flex-col">
                    <div className="text-xs font-bold text-indigo-600 uppercase mb-2">{post.category}</div>
                    <h3 className="font-bold mb-2 text-lg line-clamp-1">{post.title}</h3>
                    <p className="text-sm text-slate-600 line-clamp-3 mb-4">{post.content}</p>
                    <Link href="/blog" className="text-sm text-indigo-600 font-medium mt-auto hover:underline">Read Full Article →</Link>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>
      
      <Features />

      <section id="about" className="max-w-4xl mx-auto px-6 py-16 text-center">
        <h2 className="text-3xl font-bold mb-4">Built for Sellers, by Sellers</h2>
        <p className="text-slate-600 mb-6 max-w-2xl mx-auto">E-commerce Calculator is designed for e-commerce businesses and online sellers. Our mission is to help you calculate your actual profits after considering every expense including advertising costs, courier charges, taxes, refunds, COD charges, discounts, commissions, returns, and miscellaneous expenses.</p>
      </section>

      <FAQ />

      <footer className="bg-slate-900 text-slate-400 py-12 border-t border-slate-800">
        <div className="max-w-6xl mx-auto px-6 grid md:grid-cols-4 gap-8 mb-8">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white font-bold text-xs">EC</div>
              <span className="font-bold text-white text-lg">E-commerce Calculator</span>
            </div>
            <p className="text-sm">Pakistan's Ultimate FREE Seller Toolkit. Calculate real profits, make smarter decisions.</p>
          </div>
          <div>
            <h4 className="font-bold text-white mb-4">Product</h4>
            <ul className="space-y-2 text-sm">
              <li><a href="#" className="hover:text-white transition">All Calculators</a></li>
              <li><a href="#" className="hover:text-white transition">Profit Calculator</a></li>
              <li><a href="#" className="hover:text-white transition">ROI Calculator</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white mb-4">Resources</h4>
            <ul className="space-y-2 text-sm">
              <li><a href="#" className="hover:text-white transition">Blog</a></li>
              <li><a href="#" className="hover:text-white transition">Guides</a></li>
              <li><a href="#" className="hover:text-white transition">FAQ</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-white mb-4">Legal</h4>
            <ul className="space-y-2 text-sm">
              <li><a href="#" className="hover:text-white transition">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-white transition">Terms of Service</a></li>
              <li><a href="#" className="hover:text-white transition">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div className="max-w-6xl mx-auto px-6 border-t border-slate-800 pt-8 text-center text-sm">
          © 2026 E-commerce Calculator. All rights reserved. 100% Free Forever.
        </div>
      </footer>
    </main>
  );
}